/** Local marketing images served from /public/images (avoids third-party ORB/CORS blocks). */
export const IMAGES = {
  avatarMarcus: '/images/avatar-marcus.jpg',
  avatarJordan: '/images/avatar-jordan.jpg',
  avatarJordanB: '/images/avatar-jordan-b.jpg',
  avatarAva: '/images/avatar-ava.jpg',
  templateHouse: '/images/template-house.jpg',
  templateCoffee: '/images/template-coffee.jpg',
  templateCourtyard: '/images/template-courtyard.jpg',
  templateCity: '/images/template-city.jpg',
  templateDesk: '/images/template-desk.jpg',
  templateSkyline: '/images/template-skyline.jpg',
  contactHero: '/images/contact-hero.jpg',
  carousel1: '/images/carousel-1.jpg',
  carousel2: '/images/carousel-2.jpg',
  carousel3: '/images/carousel-3.jpg',
  carousel4: '/images/carousel-4.jpg',
  step1: '/images/step-1.jpg',
  step2: '/images/step-2.jpg',
  step3: '/images/step-3.jpg',
  step4: '/images/step-4.jpg',
  step5: '/images/step-5.jpg',
  step6: '/images/step-6.jpg',
  ultimateMindBg: '/images/ultimate-mind-bg.jpg',
} as const;
